language: r

os:
 - linux

repos:
  CRAN: https://cran.rstudio.com
  
warnings_are_errors: false

sudo: required

notifications:
 email:
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
