language: r

os:
 - linux

repos:
  CRAN: https://cran.rstudio.com
  
warnings_are_errors: false

sudo: required

notifications:
 email:
  on_failure: change

r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'library(covr); codecov()'
