codecov:
  token: e09b36f5-c951-4f86-abbb-d36a1a9ceace
  
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
